<a href="https://colab.research.google.com/github/NewTAs/GoogLeNet/blob/main/Difference_MP_GAP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Library

In [25]:
import tensorflow as tf
import tensorflow.keras

# Definition Parameter

In [26]:
global pooling, averagePooling, globalAveragePooling
pooling = None
averagePooling = None
globalAveragePooling = None

In [27]:
inputExampleLayer = (2, 3, 4, 5)

In [28]:
print(inputExampleLayer)

(2, 3, 4, 5)


# Example Layer

In [29]:
x = tf.random.normal(inputExampleLayer)
x = x * 100
pooling = x
averagePooling = x
globalAveragePooling = x
print(x)

tf.Tensor(
[[[[ -46.36564   -111.09282      2.9236796  -64.2023    -117.05663  ]
   [  62.444687     5.112976   146.14774     39.408867  -106.931175 ]
   [-214.3265     146.50893     31.22929   -256.7534      48.977654 ]
   [ 206.8547     150.219      -44.988735  -172.28683    -12.716025 ]]

  [[  95.009705    -4.662958    41.55782     -6.3900566 -118.96104  ]
   [  85.25102    -38.376556  -125.389946  -112.64056   -122.781685 ]
   [ 128.10909     28.275276    10.455992   -54.068027   101.57254  ]
   [  78.03823    -81.596924     6.334955   212.56488     67.15319  ]]

  [[  11.162882    -2.109291   126.32001    -24.284737     1.5451318]
   [ 136.4827      90.98384    -29.79185   -103.501465    46.447594 ]
   [  73.89009     67.85448   -134.24107   -116.559135    26.100285 ]
   [ -31.946001   -30.973122   158.05836    113.60099   -148.62712  ]]]


 [[[  60.439426   201.49799     27.02052     17.14576      7.025083 ]
   [ -63.33642   -215.06137     47.777645   -37.85292     96.22046  ]
 

# Result Pooling

In [30]:
y = tf.keras.layers.MaxPool2D()(pooling)
print(y)

tf.Tensor(
[[[[  95.009705    5.112976  146.14774    39.408867 -106.931175]
   [ 206.8547    150.219      31.22929   212.56488   101.57254 ]]]


 [[[  60.439426  201.49799    47.777645   54.4709     97.4149  ]
   [  94.131355  210.57922    -6.352977   89.110634  143.62439 ]]]], shape=(2, 1, 2, 5), dtype=float32)


# Result Average Pooling

In [31]:
y = tf.keras.layers.AveragePooling2D()(pooling)
print(y)

tf.Tensor(
[[[[  49.084946    -37.254837     16.309822    -35.956013
    -116.43263   ]
   [  49.66888      60.85157       0.75787544  -67.63584
      51.24684   ]]]


 [[[ -65.378914     41.66068      -6.9480877    -3.9052458
      -1.1147652 ]
   [  47.874107    -11.50466     -43.014023      0.66524696
      -2.0038643 ]]]], shape=(2, 1, 2, 5), dtype=float32)


# Result Global Average Pooling

In [32]:
y = tf.keras.layers.GlobalAveragePooling2D()(pooling)
print(y)

tf.Tensor(
[[ 48.717083   18.345232   15.718019  -45.42598   -27.939774 ]
 [  7.1367264 -13.423607  -67.36434     4.2457175  19.637    ]], shape=(2, 5), dtype=float32)
