<a href="https://colab.research.google.com/github/NewTAs/GoogLeNet/blob/main/GoogLeNet_Step3_DriveVer_Epoch50.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* 참고: https://tykimos.github.io/2017/03/08/CNN_Getting_Started/

In [1]:
# Step1 Code
import os
import re
import glob
import cv2
import numpy as np
from sklearn.model_selection import train_test_split

import tensorflow as tf

from google.colab import drive
drive.mount('googlenet')

# New Cord
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator

np.random.seed(4) # 랜덤시드 고정시키기

Mounted at googlenet


In [2]:
pictureWeightHeightSize = 227

train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        '/content/googlenet/MyDrive/GoogLeNet_Data/TrainData_Step3/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),
        batch_size=4,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        '/content/googlenet/MyDrive/GoogLeNet_Data/TestData_Step3/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=4,
        class_mode='categorical')

Found 60 images belonging to 4 classes.
Found 12 images belonging to 4 classes.


In [3]:
input_layer = tf.keras.layers.Input(shape=(227, 227, 3))

In [4]:
stem_layer = tf.keras.layers.Conv2D(32, (3, 3), strides=(1, 1), padding='SAME', activation='relu')(input_layer)
# Max Pooling Here on Original Inception (3x3, stride=2)
stem_layer = tf.keras.layers.Conv2D(64, (3, 3), strides=(1, 1), padding='SAME', activation='relu')(stem_layer)
# Max Pooling Here on Original Inception (3x3, stride=2)

In [5]:
inception_block3a_1x1 = tf.keras.layers.Conv2D(32, (1, 1), strides=(1, 1), padding='SAME', activation='relu')(stem_layer)

inception_block3a_3x3 = tf.keras.layers.Conv2D(48, (1, 1), padding='SAME', activation='relu')(stem_layer)
inception_block3a_3x3 = tf.keras.layers.Conv2D(64, (3, 3), padding='SAME', activation='relu')(inception_block3a_3x3)

inception_block3a_5x5 = tf.keras.layers.Conv2D(8, (1, 1), padding='SAME', activation='relu')(stem_layer)
inception_block3a_5x5 = tf.keras.layers.Conv2D(16, (5, 5), padding='SAME', activation='relu')(inception_block3a_5x5)

inception_block3a_pool = tf.keras.layers.MaxPool2D((3, 3), strides=(1, 1), padding='SAME')(stem_layer)
inception_block3a_pool = tf.keras.layers.Conv2D(16, (1, 1), padding='SAME', activation='relu')(inception_block3a_pool)

inception_block3a = tf.keras.layers.Concatenate()([inception_block3a_1x1, inception_block3a_3x3,
                                                   inception_block3a_5x5, inception_block3a_pool]) # 32x32x128

In [6]:
# inception_block3b Here on Original Inception
max_pool = tf.keras.layers.MaxPool2D((3, 3), strides=(2, 2), padding='SAME')(inception_block3a) # 16x16x128

In [7]:
inception_block4a_1x1 = tf.keras.layers.Conv2D(64, (1, 1), padding='SAME', activation='relu')(max_pool)

inception_block4a_3x3 = tf.keras.layers.Conv2D(64, (1, 1), padding='SAME', activation='relu')(max_pool)
inception_block4a_3x3 = tf.keras.layers.Conv2D(96, (3, 3), padding='SAME', activation='relu')(inception_block4a_3x3)

inception_block4a_5x5 = tf.keras.layers.Conv2D(16, (1, 1), padding='SAME', activation='relu')(max_pool)
inception_block4a_5x5 = tf.keras.layers.Conv2D(48, (5, 5), padding='SAME', activation='relu')(inception_block4a_5x5)

inception_block4a_pool = tf.keras.layers.MaxPool2D((3, 3), strides=(1, 1), padding='SAME')(max_pool)
inception_block4a_pool = tf.keras.layers.Conv2D(32, (1, 1), padding='SAME', activation='relu')(inception_block4a_pool)

inception_block4a = tf.keras.layers.Concatenate()([inception_block4a_1x1, inception_block4a_3x3,
                                                   inception_block4a_5x5, inception_block4a_pool]) # 16x16x240

# inception_block4b Here on Original Inception
# inception_block4c Here on Original Inception
# inception_block4d Here on Original Inception
# inception_block4e Here on Original Inception

In [8]:
max_pool = tf.keras.layers.MaxPool2D((3, 3), strides=(2, 2), padding='SAME')(inception_block4a) # 8x8x240

In [9]:
inception_block5a_1x1 = tf.keras.layers.Conv2D(128, (1, 1), padding='SAME', activation='relu')(max_pool)

inception_block5a_3x3 = tf.keras.layers.Conv2D(80, (1, 1), padding='SAME', activation='relu')(max_pool)
inception_block5a_3x3 = tf.keras.layers.Conv2D(120, (3, 3), padding='SAME', activation='relu')(inception_block5a_3x3)

inception_block5a_5x5 = tf.keras.layers.Conv2D(16, (1, 1), padding='SAME', activation='relu')(max_pool)
inception_block5a_5x5 = tf.keras.layers.Conv2D(64, (5, 5), padding='SAME', activation='relu')(inception_block5a_5x5)

inception_block5a_pool = tf.keras.layers.MaxPool2D((3, 3), strides=(1, 1), padding='SAME')(max_pool)
inception_block5a_pool = tf.keras.layers.Conv2D(64, (1, 1), padding='SAME', activation='relu')(inception_block5a_pool)

inception_block5a = tf.keras.layers.Concatenate()([inception_block5a_1x1, inception_block5a_3x3,
                                                   inception_block5a_5x5, inception_block5a_pool]) # 8x8x416
# inception_block5b Here on Original Inception

In [10]:
avg_pool = tf.keras.layers.GlobalAveragePooling2D()(inception_block5a) # 416
dropout = tf.keras.layers.Dropout(0.4)(avg_pool)
out_layer = tf.keras.layers.Dense(4, activation='softmax')(dropout)

In [11]:
model = tf.keras.models.Model(input_layer, out_layer)

#model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

#model.fit(x_train, y_train, batch_size=128, epochs=10, validation_data=(x_test, y_test))

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 227, 227, 3) 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 227, 227, 32) 896         input_1[0][0]                    
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 227, 227, 64) 18496       conv2d[0][0]                     
__________________________________________________________________________________________________
conv2d_3 (Conv2D)               (None, 227, 227, 48) 3120        conv2d_1[0][0]                   
______________________________________________________________________________________________

In [12]:
model.fit(train_generator, epochs=50, validation_data=test_generator)

Epoch 1/50
15/15 [==============================] - 70s 4s/step - loss: 1.4156 - accuracy: 0.2000 - val_loss: 1.3512 - val_accuracy: 0.2500
Epoch 2/50
15/15 [==============================] - 61s 4s/step - loss: 1.3177 - accuracy: 0.2500 - val_loss: 1.2572 - val_accuracy: 0.2500
Epoch 3/50
15/15 [==============================] - 61s 4s/step - loss: 1.1032 - accuracy: 0.4667 - val_loss: 0.9272 - val_accuracy: 0.5000
Epoch 4/50
15/15 [==============================] - 61s 4s/step - loss: 0.8386 - accuracy: 0.5833 - val_loss: 0.8630 - val_accuracy: 0.7500
Epoch 5/50
15/15 [==============================] - 61s 4s/step - loss: 0.6619 - accuracy: 0.7333 - val_loss: 0.4990 - val_accuracy: 0.7500
Epoch 6/50
15/15 [==============================] - 61s 4s/step - loss: 0.4298 - accuracy: 0.8167 - val_loss: 2.9722 - val_accuracy: 0.4167
Epoch 7/50
15/15 [==============================] - 61s 4s/step - loss: 1.2156 - accuracy: 0.5500 - val_loss: 0.6099 - val_accuracy: 0.7500
Epoch 8/50
15/15 [==

In [16]:
print("-- Evaluate --")
scores = model.evaluate(test_generator, steps=3)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
3/3 [==============================] - 2s 761ms/step - loss: 0.3043 - accuracy: 0.7500
accuracy: 75.00%


In [18]:
print("-- Predict --")
output = model.predict(test_generator, steps=3)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

-- Predict --
{'1': 0, '2': 1, '3': 2, '4': 3}
[[0.000 0.000 0.000 1.000]
 [0.295 0.704 0.000 0.001]
 [0.298 0.701 0.000 0.001]
 [0.000 0.999 0.001 0.000]
 [0.000 0.999 0.001 0.000]
 [0.296 0.703 0.000 0.001]
 [0.000 0.000 1.000 0.000]
 [0.000 0.000 1.000 0.000]
 [0.000 0.000 1.000 0.000]
 [0.000 0.998 0.002 0.000]
 [0.000 0.000 0.000 1.000]
 [0.000 0.000 0.000 1.000]]
